### ISSUE TITLE
azure-cli 2.0 preview

### ISSUE THREAD

**Issue by leitu** [Azure/azure-devops-utils#2]
Hi ,

   I'm working with azure-cli 2.0 preview a lot.. Which I revert your script to the az version, but I'm not sure if raise a PR to new branch will be fine for you? @clguimanMSFT, @arroyc 

Thanks.

**Comment by clguiman** [comment]
I recommend you create a fork and keep it up to date. We can't merge while the azure-cli 2.0 is in preview. Once it's released I think we can merge you fork back to upstream.
@arroyc what do you think?

**Comment by leitu** [comment]
fair enough :)
